### ISSUE TITLE
System Check -> File Verification

### ISSUE THREAD

**Issue by ocbroadband** [formtools/module-system_check#2]
if you do a system check -> file verification, data visualization fails as its still looking for the file with the uppercase I in the Data Visualization Module. Here's the failures on my system..

> Data Visualization: FAIL. Missing files
> 
> modules/data_visualization/code/FIeldCharts.class.php

For .gitignore, its not anywhere in the path, which looks like from the v2.x install, they are here..

Form Tools Core: FAIL. Missing files

> .gitignore
> ./modules/data_visualization/.gitignore
> ./modules/extended_client_fields/.gitignore
> ./modules/ip_security_check/.gitignore
> ./modules/submission_accounts/.gitignore
> ./modules/submission_history/.gitignore
> ./modules/submission_pre_parser/.gitignore
> ./modules/text_override/.gitignore
> ./modules/client_audit/.gitignore

**Comment by benkeen** [comment]
Thanks, @ocbroadband! This is all patched up with the latest version of the module.
