### ISSUE TITLE
System Check FT3 Beta Missing FIles

### ISSUE THREAD

**Issue by ghost** [formtools/module-system_check#4]
![image](https://user-images.githubusercontent.com/11295884/38363309-1cab2dc6-38cc-11e8-9e5a-8ea79c33d973.png)

FT3 3.0.0 Beta 20180320 SC module v 2.1.3 reports missing files for Form Builder and Swift Mailer

T

**Comment by benkeen** [comment]
Thanks @tidalfire! Sorry I missed this. 

I just released Form Builder 2.0.5 that fixed this; I'll patch the Swift Mailer one tonight.
