### ISSUE TITLE
Notice: Undefined index: email_template_id

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-system_check#5]
I had 2 orphans when I did a system check:
TABLE: bn_email_template_when_sent_views
- num orphans: 2
- error description: 
1. invalid email template ID 
2. invalid email template ID 
_______________________

When I went to "clean up" I got a blank screen - so I enabled debugging and I got:

Notice: Undefined index: email_template_id in /var/www/forms.buffalonews.com/modules/system_check/code/Orphans.class.php on line 766

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: parameter was not defined' in /var/www/forms.buffalonews.com/global/code/Database.class.php:117 Stack trace: #0 /var/www/forms.buffalonews.com/global/code/Database.class.php(117): PDOStatement->bindValue('view_id', 73, 1) #1 /var/www/forms.buffalonews.com/global/code/Database.class.php(122): FormTools\Database->bind('view_id', 73) #2 /var/www/forms.buffalonews.com/modules/system_check/code/Orphans.class.php(778): FormTools\Database->bindAll(Array) #3 /var/www/forms.buffalonews.com/modules/system_check/code/Orphans.class.php(65): FormTools\Modules\SystemCheck\Orphans::testEmailTemplateWhenSentViews(true) #4 /var/www/forms.buffalonews.com/modules/system_check/code/Orphans.class.php(151): FormTools\Modules\SystemCheck\Orphans::findTableOrphans('bn_email_templa...', true) #5 /var/www/forms.buffalonews.com/modules/system_check/orphans.php(15): FormTools\Modules\SystemCheck\Orphans::cleanOrphans() #6 {main} thrown in /var/www/forms.buffalonews.com/global/code/Database.class.php on line 117

**Comment by benkeen** [comment]
Ah, thanks @johnbleck3 - yeah I've encountered this too. Are you running 3.0.0 final (non-beta), btw? I made a patch in one of the later beta releases to fix at least one scenario where these orphans were created.

**Comment by johnbleck3** [comment]
I just updated to 3.0.0 final yesterday so yessir I am!

**Comment by benkeen** [comment]
Pretty sure this is fixed with later versions of the Core, so closing now. It can be reopened if it comes up again.
