### ISSUE TITLE
System Check FT 3.0.0 Missing Files

### ISSUE THREAD

**Issue by ghost** [formtools/module-system_check#6]
Ben,

Missing files in Core when running System Check on FT 3.0 final:

![missing_ft3_files](https://user-images.githubusercontent.com/11295884/38987643-61e13ab4-43c8-11e8-936d-862da4de8adc.jpg)

I should get out more.

T

**Comment by benkeen** [comment]
haha me too :) Thanks - I'll patch this in the next core release. It won't affect anything; it's just a file that needs updating.

**Comment by benkeen** [comment]
Closing. Will be in 3.0.1.
