### ISSUE TITLE
Module not showing up

### ISSUE THREAD

**Issue by sf23103** [formtools/module-system_check#8]
I am getting ready to upgrade to FT3, so I attempted to install the system check module.  I uploaded and extracted the module, and changed it to system_check, however it still does not show up in the module list.  I tried the refresh module list button and also tried re-uploading the folder and it still doesn't show up.  Any ideas?

**Comment by benkeen** [comment]
Hey @sf23103 did you download version `1.1.0`? That's the last compatible version for Form Tools 2.

**Comment by sf23103** [comment]
Nope.  That would help!  I don't know why I had it in my mind that the FT3 compatibility was in the latest version.  It would help if I read the notes in 1.1.0.  Thanks!!!

**Comment by benkeen** [comment]
haha no worries - it's easy to miss!
